### ISSUE TITLE
[BUG] anycastd hasn't started to publish metrics (including service_up) after service recover

### ISSUE THREAD

**Issue by teran** [runityru/anycastd#120]
**Describe the bug**

The case:
- anycastd has started
- failed some of checks
- NOT started the announcement (which is correct)
- NOT published metric for service_up (which is incorrect)

**To Reproduce**
1. start anycastd with failed service check
2. recover the service

**Expected behavior**

While service checks are failed: service_up must be published and equal 0
While service checks are ok/recovered: service_up must be published and equal 1

**Configuration file snippet**

```
services:
  - name: http
    check_interval: 10s
    checks:
      - kind: http_2xx
        spec:
          url: http://127.0.0.1:9999/ping
          method: GET
          tries: 3
          interval: 100ms
          timeout: 2s
      - kind: http_2xx
        spec:
          url: http://{anycast address}/health-probe-bucket/probe
          method: GET
          tries: 3
          interval: 5s
          timeout: 5s
      - kind: assigned_address
        spec:
          interface: dummy0
          ipv4: {anycast address}
      - kind: tls_certificate
        spec:
          local:
            path: {certificate path}
```

**Peer routers:**

 N/A

**Additional context**

N/A
